name: Build and deploy Next.js app to Azure Web App - Portfolio-website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️ Checkout repo
      - uses: actions/checkout@v4

      # 2️ Set Node.js version
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3️ Install dependencies
      - name: Install dependencies
        run: npm install

      # 4️ Build Next.js app
      - name: Build app
        run: npm run build

      # 5️ Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_92C94E16C1ED4B0483E631021BCB9B39 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B19BF0B5CC8240069BCF8693A38B2856 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B4088ACDB83B4597B1C6B0FF89DDC249 }}

      # 6️ Deploy built app to Azure
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'Portfolio-website'
          slot-name: 'Production'
          package: '.'
